config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, except: :show do
    resources :tasks, except: :show do
      resources :execution_periods, only: %i[create update]

      member do
        post :complete
        post :proceed
      end
    end
  end

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tasks
end

app/models/execution_period.rb
class ExecutionPeriod < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :execution_periods

	scope :finished,-> { where(finished: true) }	
	scope :unfinished,-> { where(finished: false) }	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
	def index
		@categories = current_user.categories
	end

	def new
		@category = current_user.categories.new
	end

	def create
		current_user.categories.create(category_params)

    redirect_to root_path
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/execution_periods_controller.rb
# frozen_string_literal: true

class ExecutionPeriodsController < ApplicationController
	def create
		task = Task.find(params[:task_id])
		task.execution_periods.create(start_time: Time.now)

    redirect_to root_path
	end

	def update
		execution_period = ExecutionPeriod.find(params[:id])
		time_now = Time.now
		duration = time_now - execution_period.start_time
		execution_period.update(end_time: time_now, duration: duration)
		
		redirect_to root_path
	end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
	before_action :set_task, only: %i[edit update destroy complete proceed]

	def index
		@finished_tasks = current_user.tasks.finished.includes(:execution_periods)
		@unfinished_tasks = current_user.tasks.unfinished.includes(:execution_periods)
		@durations = current_user.tasks.includes(:execution_periods).group('tasks.id').sum(:duration)
	end

	def new
		@task = current_user.tasks.new
	end

	def create
		current_user.tasks.create(task_params)

    redirect_to root_path
	end

	def edit; end

	def update
		@task.update(task_params)

		redirect_to root_path
	end

	def destroy
		@task.delete

		redirect_to root_path
	end

	def complete
		@task.update(finished: true)

		redirect_to root_path
	end

	def proceed
		@task.update(finished: false)

		redirect_to root_path
	end

	private

	def task_params
    params.require(:task).permit(:name)
  end

  def set_task
  	@task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%= link_to 'New category', new_category_path %>

<% @categories.each do |category| %>
	<div>
		<%= category.name %>
	</div>
<% end %>

app/views/categories/new.html.erb
<%= form_with model: @category, local: true do |form| %>
	<%= form.text_field :name, class: :input %>
	<%= form.submit('Create') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task, local: true do |form| %>
	<%= form.text_field :name, class: :input %>
	<%= form.submit('Update') %>
<% end %>

app/views/tasks/index.html.erb
<%= link_to 'New task', new_task_path %>

<% @unfinished_tasks.each do |task| %>
	<div>
		<%= task.name %>
		<%= "Duration: #{ActiveSupport::Duration.build(@durations[task.id]).inspect}" %>
		<%= link_to 'Start', task_execution_periods_path(task_id: task.id), data: { turbo_method: :post } %>	
		<%= link_to 'Complete', complete_task_path(task), data: { turbo_method: :post } %>
		<%= link_to 'Edit', edit_task_path(id: task.id) %>
		<%= link_to 'Delete', task_path(task), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>

		<% task.execution_periods.each do |execution_period| %>
			<%= "#{execution_period.start_time} - #{execution_period.end_time}" %>

			<% if execution_period.end_time.nil? %>
				<%= link_to 'Finish', task_execution_period_path(id: execution_period.id, task_id: task.id), data: { turbo_method: :patch } %>	
			<% else %>
				<%= ActiveSupport::Duration.build(execution_period.duration).inspect %>
			<% end %>
		<% end %>
	</div>
<% end %>

<br>

<% @finished_tasks.each do |task| %>
	<div>
		<%= task.name %>
		<%= "Duration: #{ActiveSupport::Duration.build(@durations[task.id]).inspect}" %>
		<%= link_to 'Proceed', proceed_task_path(task), data: { turbo_method: :post } %>
		<%= link_to 'Edit', edit_task_path(id: task.id) %>
		<%= link_to 'Delete', task_path(task), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>

		<% task.execution_periods.each do |execution_period| %>
			<%= "#{execution_period.start_time} - #{execution_period.end_time}" %>

			<% if execution_period.end_time.nil? %>
				<%= link_to 'Finish', task_execution_period_path(id: execution_period.id, task_id: task.id), data: { turbo_method: :patch } %>	
			<% else %>
				<%= ActiveSupport::Duration.build(execution_period.duration).inspect %>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/tasks/new.html.erb
<%= form_with model: @task, local: true do |form| %>
	<%= form.text_field :name, class: :input %>
	<%= form.submit('Create') %>
<% end %>